import { mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { prepareGenerationRoot } from '../src/host/workspace.js'

const created: string[] = []
afterEach(() => {
  for (const directory of created.splice(0)) rmSync(directory, { recursive: true, force: true })
})

describe('generation workspace', () => {
  it('writes the Cordis root into the Shell-owned absolute directory', () => {
    const directory = mkdtempSync(join(tmpdir(), 'dsh-station-test-'))
    created.push(directory)
    const root = prepareGenerationRoot(directory)
    expect(root).toBe(join(directory, 'cordis.yml'))
    expect(readFileSync(root, 'utf8')).toContain('Generated by DeepSeek Harness Station')
  })

  it('rejects relative working directories', () => {
    expect(() => prepareGenerationRoot('relative-generation')).toThrow(/absolute path/)
  })
})
