/** Independent DeepSeek Harness Host controlled through a private process channel. */

import { writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import type { Context } from '@deepseek-ai/cordis'
import type { PatchOptions } from '@deepseek-ai/cordis-plugin-include'
import {
  boot,
  healProfilesModuleFallback,
  loadLayeredEnv,
  loadOptionalPatches,
  loadProfile,
  PROFILE_PATCH_FILENAME,
} from '@deepseek-ai/dsh-app-boot'
import { provideCmdline } from '@deepseek-ai/dsh-cmdline'
import { resolveDshHome } from '@deepseek-ai/dsh-home-paths'
import { DSH_LAUNCH_ENVIRONMENT_KEY } from '@deepseek-ai/dsh-launch-environment'
import type {} from '@deepseek-ai/dsh-host-webserver'
import {
  parseShellMessage,
  STATION_PROTOCOL_VERSION,
  type HostToShellMessage,
  type StartHostCommand,
} from '../protocol.ts'

const NAME = 'dsh-station-host'
const ROOT_CONFIG = 'cordis.yml'
const EMPTY_ROOT = '# Generated by DSH Station. Profile layers are applied over this empty root.\n[]\n'
const require = createRequire(import.meta.url)

function send(message: HostToShellMessage): void {
  process.send?.(message)
}

function installationAnchor(): string {
  return require.resolve('@deepseek-ai/dsh/package.json')
}

function composeProfile(profileName: string): { root: string; patches: PatchOptions[]; anchor: string } {
  const anchor = installationAnchor()
  healProfilesModuleFallback(anchor)
  const profile = loadProfile(NAME, profileName, anchor)
  const root = join(profile.dir, ROOT_CONFIG)
  writeFileSync(root, EMPTY_ROOT)
  const homeLayer = loadOptionalPatches(NAME, join(resolveDshHome(), PROFILE_PATCH_FILENAME)) ?? []
  return {
    root,
    anchor,
    patches: structuredClone([
      ...profile.layers.flatMap(layer => layer.patches),
      ...profile.patches,
      ...homeLayer,
    ]),
  }
}

async function bootHost(command: StartHostCommand): Promise<Context> {
  const profile = composeProfile(command.profile)
  const environment = loadLayeredEnv(NAME)
  return await boot(NAME, profile.root, profile.patches, (ctx) => {
    ctx.provide(DSH_LAUNCH_ENVIRONMENT_KEY, environment)
    provideCmdline(ctx, {
      args: ['--host', '127.0.0.1', '--port', '0'],
      exit: () => { void ctx.fiber.dispose() },
    })
  }, pathToFileURL(profile.anchor).href)
}

let active: { generationId: string; context: Context } | undefined
let starting = false

async function stop(generationId: string): Promise<void> {
  if (active?.generationId !== generationId) return
  const context = active.context
  active = undefined
  await context.fiber.dispose()
  send({ type: 'stopped', generationId })
}

process.on('message', (raw: unknown) => {
  const message = parseShellMessage(raw)
  if (message === undefined) return
  if (message.type === 'stop') {
    void stop(message.generationId)
    return
  }
  if (starting || active !== undefined) {
    send({ type: 'failed', generationId: message.generationId, message: 'Host already owns a generation' })
    return
  }
  starting = true
  void bootHost(message).then((context) => {
    starting = false
    const webServer = context.get('webServer')
    if (webServer === undefined) throw new Error('Web profile activated without the webServer service')
    active = { generationId: message.generationId, context }
    send({
      type: 'ready',
      protocolVersion: STATION_PROTOCOL_VERSION,
      generationId: message.generationId,
      origin: `http://127.0.0.1:${String(webServer.port)}`,
    })
  }).catch((cause: unknown) => {
    starting = false
    send({
      type: 'failed',
      generationId: message.generationId,
      message: cause instanceof Error ? cause.message : String(cause),
    })
  })
})

async function shutdown(): Promise<void> {
  if (active !== undefined) await stop(active.generationId)
  process.exit(0)
}

process.once('disconnect', () => { void shutdown() })
process.once('SIGTERM', () => { void shutdown() })
process.once('SIGINT', () => { void shutdown() })
