/** Generation-scoped writable files owned by the Shell supervisor. */

import { mkdirSync, writeFileSync } from 'node:fs'
import { isAbsolute, join } from 'node:path'

const ROOT_CONFIG = 'cordis.yml'
const EMPTY_ROOT = '# Generated by DeepSeek Harness Station. Profile layers are applied over this empty root.\n[]\n'

/** Create the minimal Cordis root in a Shell-provided absolute working directory. */
export function prepareGenerationRoot(workDir: string): string {
  if (!isAbsolute(workDir)) throw new Error('Host workDir must be an absolute path')
  mkdirSync(workDir, { recursive: true })
  const root = join(workDir, ROOT_CONFIG)
  writeFileSync(root, EMPTY_ROOT, { encoding: 'utf8', flag: 'wx' })
  return root
}
